[versions]
paper-api-1_19_4 = "1.19.4-R0.1-SNAPSHOT"
minimessage = "4.26.1"
placeholder-api= "2.12.2"
h2 = "2.2.224"
gson = "2.10.1"
minecraft-runtime = "1.19.4"
run-task = "3.0.2"
shadow = "9.4.1"
folia-api = "26.1.2.build.746-stable"
netty = "4.2.16.Final"
## Compability with other Plugins
modelEngine= "R4.1.0"
betterModel= "3.2.0"
itemsAdder= "4.0.18-beta-10"
craftEngine= "26.7"
mmoitems= "6.10.1-SNAPSHOT"
mythiclib= "1.7.1-SNAPSHOT"
mmocore= "1.13.1-SNAPSHOT"

# Obfuscation
proguard = "7.9.1"

[libraries]
proguardGradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }
paperApiV1194 = { module = "io.papermc.paper:paper-api", version.ref = "paper-api-1_19_4" }
miniMessageLib= { module = "net.kyori:adventure-text-minimessage", version.ref = "minimessage" }
h2SqlLib = { module = "com.h2database:h2", version.ref = "h2" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
papi = { module= "me.clip:placeholderapi", version.ref = "placeholder-api" }
foliaApi = { module= "io.canvasmc.canvas:canvas-api", version.ref = "folia-api" }
netty = { module = "io.netty:netty-all", version.ref = "netty" }
## Compability with other Plugins
modelEngineApi= { module= "com.ticxo.modelengine:ModelEngine", version.ref = "modelEngine" }
betterModelApi= { module= "io.github.toxicity188:bettermodel-api", version.ref = "betterModel" }
betterModelBukkitApi= { module= "io.github.toxicity188:bettermodel-bukkit-api", version.ref = "betterModel" }
itemsAdderApi= { module= "beer.devs:itemsadder-api", version.ref = "itemsAdder" }
craftEngineBukkitApi= { module= "net.momirealms:craft-engine-bukkit", version.ref = "craftEngine" }
craftEngineCoreApi= { module= "net.momirealms:craft-engine-core", version.ref = "craftEngine" }
mmoitemsApi= { module= "net.Indyuce:MMOItems-API", version.ref = "mmoitems" }
mythiclibApi= { module= "io.lumine:MythicLib-dist", version.ref = "mythiclib" }
mmocoreApi= { module= "net.Indyuce:MMOCore-API", version.ref = "mmocore" }
[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
run-shadow = { id = "com.gradleup.shadow", version.ref = "shadow"}

