# MMOBlock configuration file version 26.7.31
debug: false # logging debug info to console
bStats: true # send anonymous stats to bStats
updateChecker: true # check for updates on https://voxel.shop/

# Database configuration
databases:
  mysql:
    enabled: false
    host: localhost
    port: 3306
    database: voxelshop
    username: root
    password: password
  h2:
    enabled: true
    file: .caches/data

# Interaction configuration
interactionThrottleMs: 1000 # throttle interactions with blocks and entities to prevent spamming. Time in milliseconds.
interaction:
  real-block-radius: 12     # Radius (blocks) within which PlayerInteractEvent handles MMOBlock clicks. Beyond this, packet-level interception is used.
  fake-block-radius: 64    # Radius (blocks) within which packet-level click interception works. Beyond this, no click processing.

# Progress bar configuration
progressbar:
  progressing: "&a|"
  noprogress: "<gray>|</gray>"
  barlength: 16

# Hologram configuration
hologram:
  packet:
    maxUpdatesPerTick: 200
    spacing:
      text: 0.25
      item: 0.40
      block: 0.30
    offset:
      text: 0.00
      item: 0.00
      block: 0.00
