name: MMOBlock
version: '${version}'
main: me.chyxelmc.mmoblock.MMOBlock
author: Aniko
website: chyxelmc.me
api-version: '1.19'
load: POSTWORLD
folia-supported: true
softdepend:
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - PlaceholderAPI
  - ModelEngine
  - BetterModel
  - ItemsAdder
  - CraftEngine
  - MMOItems
  - MMOCore
  - Minepacks

permissions:
  mmoblock.admin:
    description: Allows using MMOBlock admin commands
    default: op

commands:
  mmoblock:
    description: Manage MMOBlock interaction entities
    usage: /<command> block | /<command> block <place|remove|get|list> | /<command> reload [config|blocks|nodes|drops|lang|tools] | /<command> node [place|remove|list] <nodeId> x y z world facing
